/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EffectType = IDL.Variant({
  'trail' : IDL.Null,
  'glow' : IDL.Null,
  'none' : IDL.Null,
});
export const ShapeType = IDL.Variant({
  'circle' : IDL.Null,
  'square' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CursorConfig = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'size' : IDL.Nat,
  'effect' : EffectType,
  'shape' : ShapeType,
  'image' : ExternalBlob,
  'opacity' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteCursor' : IDL.Func([IDL.Text], [], []),
  'getCursor' : IDL.Func([IDL.Text], [CursorConfig], ['query']),
  'listCursors' : IDL.Func([], [IDL.Vec(CursorConfig)], ['query']),
  'saveCursorConfig' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Float64,
        EffectType,
        ShapeType,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EffectType = IDL.Variant({
    'trail' : IDL.Null,
    'glow' : IDL.Null,
    'none' : IDL.Null,
  });
  const ShapeType = IDL.Variant({ 'circle' : IDL.Null, 'square' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CursorConfig = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'size' : IDL.Nat,
    'effect' : EffectType,
    'shape' : ShapeType,
    'image' : ExternalBlob,
    'opacity' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteCursor' : IDL.Func([IDL.Text], [], []),
    'getCursor' : IDL.Func([IDL.Text], [CursorConfig], ['query']),
    'listCursors' : IDL.Func([], [IDL.Vec(CursorConfig)], ['query']),
    'saveCursorConfig' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Float64,
          EffectType,
          ShapeType,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };